In [1]:
import pandas as pd

In [3]:
from lxml import etree
parser = etree.XMLParser(recover=True)
tree = etree.parse(file_path, parser=parser)
root = tree.getroot()

# Extracting information into a DataFrame
rows = []
df_columns = ["ID", "URL", "Headline", "Dateline", "Text"]

for sabanews in root.findall('Sabanews'):
    data = []
    for elem in df_columns:
        data.append(sabanews.find(elem).text if sabanews.find(elem) is not None else None)
    rows.append(data)

df_from_file = pd.DataFrame(rows, columns=df_columns)
df_from_file.head()  # Display the first few rows of the DataFrame from file

ID                                        URL  \
0  SBN_ARB_0000001  http://www.sabanews.net/ar/news200024.htm   
1  SBN_ARB_0000002  http://www.sabanews.net/ar/news200066.htm   
2  SBN_ARB_0000003  http://www.sabanews.net/ar/news200073.htm   
3  SBN_ARB_0000004  http://www.sabanews.net/ar/news200090.htm   
4  SBN_ARB_0000005  http://www.sabanews.net/ar/news200092.htm   

                                            Headline        Dateline  \
0  الكونجرس الأمريكي يطالب المجتمع الدولي دعم الي...  08/ديسمبر/2009   
1  مناقشة إستراتيجية التواصل الخاصة بالأجندة الوط...  08/ديسمبر/2009   
2  نائب وزير التخطيط يلتقي بعثة الوكالة اليابانية...  08/ديسمبر/2009   
3  الناطق الرسمي: الرؤية الحكيمة للدولة في التعام...  08/ديسمبر/2009   
4        نوكيا تطرح خدمة الخرائط والملاحة في الأسواق  08/ديسمبر/2009   

                                                Text  
0  08/ديسمبر/2009] واشنطن ـ سبأنت: طالب الكونجرس ...  
1  08/ديسمبر/2009] صنعاء ـ سبأنت: جرى اليوم بوزار...  
2  08/ديسمبر/2009] صنعاء ـ سبأنت: أشاد نائب وزير ...  
3  08/ديسمبر/2009] صنعاء – سبأنت : أكد الناطق الر...  
4  08/ديسمبر/2009] القاهرة ـ سبأنت: عبداللطيف الك...

In [4]:
df_from_file['Text'][0]

'08/ديسمبر/2009] واشنطن ـ سبأنت: طالب الكونجرس الأمريكي الإدارة الأمريكية والمجتمع الدولي تقديم الدعم والمساعدة لليمن بما يمكنه من مواجهة التحديات القائمة وتعزيز مسيرته التنموية . و دعا مجلس الشيوخ الأمريكي في قرار أصدره مؤخرا و صوت عليه أغلبية أعضائه, الرئيس الأمريكي باراك أوباما إلى دعم التنمية و الإصلاحات في اليمن.. مشددا على أهمية عدم تجاهل التحديات التي تواجهها اليمن في الآونة الأخيرة. ونبه مجلس الشيوخ الأمريكي في هذا الصدد إلى التهديدات الخطيرة التي يتعرض لها الأمن القومي الأمريكي واليمن ودول المنطقة بسبب ظاهرة الإرهاب وزعزعة الاستقرار في اليمن. وأكد وقوفه إلى جانب أمن و سلامة المواطنين اليمنيين المتضررين جراء المواجهات القائمة بما في ذلك النازحين من المدنيين الأبرياء الذين عانوا جراء الأحداث المزعزعة للاستقرار والعمليات الإرهابية. ودعا المجلس الإدارة الأمريكية و المجتمع الدولي مساعدة اليمن بكل السبل المتاحة لتعزيز قدراته في مواجهة الإرهاب والحيلولة دون تدهور أوضاعه الأمنية والحفاظ على استقراره. في حين شدد السيناتور الديمقراطي بنجامين كاردان الذي تبنى القرار مع السيناتور الجمهوري

In [9]:
text = ''.join(df_from_file['Text'].values)
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print("Vocab_size = ", vocab_size)

 !"$%'()*+,-./0123456789:;=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]_`abcdefghijklmnopqrstuvwxyz{|}~§«­·»×÷،؛؟ءآأؤإئابةتثجحخدذرزسشصضطظعغـفقكلمنهوىيًٌٍَُِّْچکھ‌‍‎‏–—‘’“”•…
Vocab_size =  160


In [10]:
char_toid = { ch:i for i,ch in enumerate(chars)}
id_tochar = { i:ch for i,ch in enumerate(chars)}

encode = lambda s: [char_toid[c] for c in s]
decode = lambda ids: [id_tochar[id] for id in ids]

print(encode("و صوت عليه أغلبية أعضائه"))
print(''.join(decode(encode("و صوت عليه أغلبية أعضائه"))))

[134, 0, 120, 134, 109, 0, 124, 130, 136, 133, 0, 102, 125, 130, 107, 136, 108, 0, 102, 124, 121, 106, 105, 133]
و صوت عليه أغلبية أعضائه


In [12]:
import torch

data = torch.tensor(encode(text), dtype=torch.long)
print(data[0:1000])

tensor([ 14,  22,  13, 114, 136, 118, 131, 107, 116,  13,  16,  14,  14,  23,
         57,   0, 134, 106, 119, 132, 122, 132,   0, 126,   0, 118, 107, 102,
        132, 109,  24,   0, 122, 106, 130, 107,   0, 106, 130, 129, 134, 132,
        111, 116, 118,   0, 106, 130, 102, 131, 116, 136, 129, 136,   0, 106,
        130, 104, 114, 106, 116, 108,   0, 106, 130, 102, 131, 116, 136, 129,
        136, 108,   0, 134, 106, 130, 131, 111, 109, 131, 124,   0, 106, 130,
        114, 134, 130, 136,   0, 109, 128, 114, 136, 131,   0, 106, 130, 114,
        124, 131,   0, 134, 106, 130, 131, 118, 106, 124, 114, 108,   0, 130,
        130, 136, 131, 132,   0, 107, 131, 106,   0, 136, 131, 129, 132, 133,
          0, 131, 132,   0, 131, 134, 106, 111, 133, 108,   0, 106, 130, 109,
        112, 114, 136, 106, 109,   0, 106, 130, 128, 106, 105, 131, 108,   0,
        134, 109, 124, 117, 136, 117,   0, 131, 118, 136, 116, 109, 133,   0,
        106, 130, 109, 132, 131, 134, 136, 108,   0,  12,   0, 1

In [14]:
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

In [15]:
block_size=8
train_data[:block_size+1]

tensor([ 14,  22,  13, 114, 136, 118, 131, 107, 116])

In [16]:
x = train_data[:block_size]
y = train_data[1:block_size+1]

for t in range(block_size):
    context = x[:t+1]
    target = y[t]

    print(f"when input is {context} the target: {target}")

when input is tensor([14]) the target: 22
when input is tensor([14, 22]) the target: 13
when input is tensor([14, 22, 13]) the target: 114
when input is tensor([ 14,  22,  13, 114]) the target: 136
when input is tensor([ 14,  22,  13, 114, 136]) the target: 118
when input is tensor([ 14,  22,  13, 114, 136, 118]) the target: 131
when input is tensor([ 14,  22,  13, 114, 136, 118, 131]) the target: 107
when input is tensor([ 14,  22,  13, 114, 136, 118, 131, 107]) the target: 116


In [25]:
torch.manual_seed(1337)
batch_size=4
block_size=8

def get_batch(split):
    data = train_data if split=='train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])

    return x, y

xb, yb = get_batch("train")
print('Input: ')
print(xb.shape)
print(xb)

print('Targets: ')
print(yb.shape)
print(yb)

print("----")
for b in range(batch_size):
    for t in range(block_size):
        context = xb[b, :t+1]
        target = yb[b, t]

        print(f"when input is {context.tolist()} the target: {target}")

Input: 
torch.Size([4, 8])
tensor([[124,   0, 106, 130, 106, 132, 106, 116],
        [132,   0, 106, 130, 115, 136,   0, 106],
        [112, 109, 131, 130, 108,   2,   0, 127],
        [  0, 134, 106, 112, 114, 106,   0, 131]])
Targets: 
torch.Size([4, 8])
tensor([[  0, 106, 130, 106, 132, 106, 116, 108],
        [  0, 106, 130, 115, 136,   0, 106, 128],
        [109, 131, 130, 108,   2,   0, 127, 136],
        [134, 106, 112, 114, 106,   0, 131, 132]])
----
when input is [124] the target: 0
when input is [124, 0] the target: 106
when input is [124, 0, 106] the target: 130
when input is [124, 0, 106, 130] the target: 106
when input is [124, 0, 106, 130, 106] the target: 132
when input is [124, 0, 106, 130, 106, 132] the target: 106
when input is [124, 0, 106, 130, 106, 132, 106] the target: 116
when input is [124, 0, 106, 130, 106, 132, 106, 116] the target: 108
when input is [132] the target: 0
when input is [132, 0] the target: 106
when input is [132, 0, 106] the target: 130
when inp

In [26]:
xb

tensor([[124,   0, 106, 130, 106, 132, 106, 116],
        [132,   0, 106, 130, 115, 136,   0, 106],
        [112, 109, 131, 130, 108,   2,   0, 127],
        [  0, 134, 106, 112, 114, 106,   0, 131]])

In [36]:
import torch 
import torch.nn as nn
from torch.nn import functional as F

torch.manual_seed(2024)

class BigramLanguageModel(nn.Module):
    
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, target=None):

        logits = self.token_embedding_table(idx) # (Batch, Time, Channel). Channel is coming from the Embedding layer for each one of the input
        
        if target is None:
            return logits, None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C) # This squach the two first dimensions B and T so that C is the second to comply with cross entropy
            target = target.view(B*T)
            loss = F.cross_entropy(logits, target) # Cross entropy would expect (Batch, Channel, Time)
            return logits, loss
    
    def generate(self, idx, max_new_tokens):

        for _ in range(max_new_tokens):
            logits, loss = self(idx) # Get the prediction

            logits = logits[:, -1, :] # Focus only on the last timestep => (B, C) because T becomes 1

            probs = F.softmax(logits, dim=-1)  # Apply softmax converts to probabilites across the Channels

            idx_next = torch.multinomial(probs, num_samples=1) # We sample from the prob distribution to get the next token (B, 1)

            idx = torch.cat((idx, idx_next), dim=1) # Concatenate the token with the existing sequence (B, T+1)
        
        return idx

m = BigramLanguageModel(vocab_size=vocab_size)
out, loss = m(xb, yb)
print(out.shape)
print(f"Loss {loss}")


print(''.join(decode(m.generate(idx=torch.zeros((1,1), dtype=torch.long), max_new_tokens=100)[0].tolist())))

torch.Size([32, 160])
Loss 5.571990013122559
 ““cظLج­ـ-«Q5fة1صئ07س’_I%إ…TgJىلف[@ه}…ئ8Kذ0XأPLT’5fّ$tZ$ع:­إ(}ؤ$a?fEحA:ّY‍Fرn_ؤ| C5“«"bْع؟لصصBوف?o"Sع


In [37]:
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

/Users/mehditantaoui/Documents/Challenges/GenerativeAI/transformers/.venv/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [40]:
batch_size = 32

for steps in range(10000):

    xb, yb = get_batch("train")

    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())

2.481208324432373


In [41]:
print(''.join(decode(m.generate(idx=torch.zeros((1,1), dtype=torch.long), max_new_tokens=100)[0].tolist())))

 كلوان د تعن الحرية حالأنهد انستفة الإلق "صرة فا عالالللار. الميحاسبدن سوحاجاء بعز بة الحرضحزيلك، الى
